# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3125517766608113dd7fc8e6e99b16a639d8e10b6c9430ccf1849170b9239ecbbb7ead3699ccc060369db6f94a8eacaaeec0d1d6053147dc54c7181a5ca38278

test:
  secret_key_base: f8b992893a9420c11fa1204fc314dbc0841ec90f7434c445f6c6ab52830722cb0aadc9618ee1a0193e5b399b3da7e024a9b0e2d01c753945c9ca2fb41833f7c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
